param(
    [switch]$Apply
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ClaudeHome = Join-Path $HOME ".claude"
$LocalSettings = Join-Path $ClaudeHome "settings.local.json"
$ActiveSettings = Join-Path $ClaudeHome "settings.json"
$GeneratedSettings = Join-Path $Root ".claude/settings.generated.json"
$Python = (Get-Command python3 -ErrorAction SilentlyContinue)
if (-not $Python) { $Python = Get-Command py -ErrorAction Stop }

function Install-Link([string]$Source, [string]$Target) {
    if (Test-Path $Target) {
        $item = Get-Item $Target -Force
        if ($item.LinkType -and $item.Target -eq $Source) {
            Write-Host "ok      $Target"
            return
        }
        throw "conflict $Target already exists; move or merge it manually"
    }
    if ($Apply) {
        New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Target) | Out-Null
        New-Item -ItemType SymbolicLink -Path $Target -Target $Source | Out-Null
        Write-Host "linked  $Target -> $Source"
    } else {
        Write-Host "would   $Target -> $Source"
    }
}

# Claude Code discovers skills and agents by name inside a shared directory that
# other tools also install into. Linking the directory itself would make any
# pre-existing entry an unresolvable conflict, so each entry is linked
# individually and unrelated neighbours are left alone.
function Install-Children([string]$SourceDir, [string]$TargetDir) {
    if ($Apply) {
        New-Item -ItemType Directory -Force -Path $TargetDir | Out-Null
    }
    foreach ($child in Get-ChildItem -Force -Path $SourceDir) {
        Install-Link $child.FullName (Join-Path $TargetDir $child.Name)
    }
}

Write-Host ("Portable Claude Code bootstrap ({0})" -f $(if ($Apply) { "apply" } else { "dry-run" }))

# Claude Code owns settings.json and writes settings.local.json on its own, so
# neither file existing is a conflict. Anything in settings.json that this
# repository did not generate is unmanaged and gets folded into the overlay
# instead of being discarded. A byte-identical match against the last generated
# file is how a previous apply is recognized, which keeps portable values from
# being baked into the overlay on every rerun.
$Carry = $null
if (Test-Path $ActiveSettings) {
    $Generated = (Test-Path $GeneratedSettings) -and
        -not (Compare-Object (Get-Content $ActiveSettings) (Get-Content $GeneratedSettings))
    if ($Generated) {
        Write-Host "ok      $ActiveSettings was generated by this repository"
    } else {
        $Carry = $ActiveSettings
        Write-Host "would   fold unmanaged $ActiveSettings into $LocalSettings"
    }
}

if ($Apply) {
    if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
        throw "Claude Code CLI is required for -Apply; install it and rerun."
    }
    $SyncArgs = @(
        (Join-Path $Root "scripts/sync_config.py"),
        "--base", (Join-Path $Root ".claude/settings.json"),
        "--local", $LocalSettings,
        "--output", $GeneratedSettings
    )
    if ($Carry) { $SyncArgs += @("--carry", $Carry) }
    & $Python.Source @SyncArgs
    New-Item -ItemType Directory -Force -Path $ClaudeHome | Out-Null
    Copy-Item $GeneratedSettings $ActiveSettings
} else {
    Write-Host "would   merge portable settings with $LocalSettings"
    Write-Host "would   install merged settings at $ActiveSettings"
}

Install-Link (Join-Path $Root "CLAUDE.global.md") (Join-Path $ClaudeHome "CLAUDE.md")
Install-Link (Join-Path $Root ".claude/hooks") (Join-Path $ClaudeHome "hooks")
Install-Children (Join-Path $Root ".claude/agents") (Join-Path $ClaudeHome "agents")
Install-Children (Join-Path $Root "skills") (Join-Path $ClaudeHome "skills")

if ($Apply) {
    & claude mcp add --transport http --scope user context7 https://mcp.context7.com/mcp
    & claude mcp add --transport stdio --scope user codebase_memory -- npx -y codebase-memory-mcp@0.8.1
    if ($env:GITHUB_PAT_TOKEN) {
        $Github = '{"type":"http","url":"https://api.githubcopilot.com/mcp/","headers":{"Authorization":"Bearer ${GITHUB_PAT_TOKEN}"}}'
        & claude mcp add-json --scope user github $Github
    }
} else {
    Write-Host "would   add user MCP servers: context7, codebase_memory"
    Write-Host "would   add user MCP server github only when GITHUB_PAT_TOKEN is set"
    Write-Host "Dry-run only. Install Claude Code, then rerun with -Apply after resolving conflicts."
}
