#!/usr/bin/env bash
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
APPLY=false
action_seen=false
conflicts=0
LOCAL_SETTINGS="$HOME/.claude/settings.local.json"
GENERATED_SETTINGS="$ROOT/.claude/settings.generated.json"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run)
      [ "$action_seen" = false ] || { echo "usage: scripts/bootstrap.sh [--dry-run|--apply]" >&2; exit 2; }
      action_seen=true
      APPLY=false
      ;;
    --apply)
      [ "$action_seen" = false ] || { echo "usage: scripts/bootstrap.sh [--dry-run|--apply]" >&2; exit 2; }
      action_seen=true
      APPLY=true
      ;;
    *)
      echo "usage: scripts/bootstrap.sh [--dry-run|--apply]" >&2
      exit 2
      ;;
  esac
  shift
done

find_python() {
  # tomllib landed in 3.11 and the validator imports it, so a bare `python3`
  # check passes on the 3.9 interpreters that ship with several long-term-support
  # distributions and then fails later with an unrelated import error.
  found=false
  for candidate in "${PYTHON:-}" python3 python3.13 python3.12 python3.11; do
    [ -n "$candidate" ] || continue
    command -v "$candidate" >/dev/null 2>&1 || continue
    found=true
    if "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)' 2>/dev/null; then
      echo "$candidate"
      return 0
    fi
  done
  if [ "$found" = true ]; then
    echo "Python 3.11 or newer is required; found $(python3 --version 2>&1)" >&2
  else
    echo "Python 3.11 or newer is required; no python3 interpreter was found" >&2
  fi
  return 1
}

PYTHON=$(find_python)
if [ "$APPLY" = true ] && ! command -v claude >/dev/null 2>&1; then
  echo "Claude Code CLI is required for --apply; install it and rerun." >&2
  exit 1
fi

link_item() {
  source_path=$1
  target_path=$2
  if [ -L "$target_path" ]; then
    current=$(readlink "$target_path")
    if [ "$current" = "$source_path" ]; then
      echo "ok      $target_path"
      return
    fi
    echo "conflict $target_path -> $current" >&2
    return 1
  fi
  if [ -e "$target_path" ]; then
    echo "conflict $target_path already exists; move or merge it manually" >&2
    return 1
  fi
  if [ "$APPLY" = true ]; then
    mkdir -p "$(dirname -- "$target_path")"
    ln -s "$source_path" "$target_path"
    echo "linked  $target_path -> $source_path"
  else
    echo "would   $target_path -> $source_path"
  fi
}

link_children() {
  # Claude Code discovers skills and agents by name inside a shared directory
  # that other tools also install into. Linking the directory itself would make
  # any pre-existing entry an unresolvable conflict, so each entry is linked
  # individually and unrelated neighbours are left alone.
  source_dir=$1
  target_dir=$2
  status=0
  if [ "$APPLY" = true ]; then
    mkdir -p "$target_dir"
  fi
  for source_path in "$source_dir"/*; do
    [ -e "$source_path" ] || continue
    link_item "$source_path" "$target_dir/$(basename -- "$source_path")" || status=1
  done
  return "$status"
}

install_settings() {
  target="$HOME/.claude/settings.json"
  # Claude Code owns settings.json and writes settings.local.json on its own, so
  # neither file existing is a conflict. Anything in settings.json that this
  # repository did not generate is unmanaged and gets folded into the overlay
  # instead of being discarded. A byte-identical match against the last
  # generated file is how a previous apply is recognized, which keeps portable
  # values from being baked into the overlay on every rerun.
  carry=""
  if [ -e "$target" ]; then
    if [ -e "$GENERATED_SETTINGS" ] && cmp -s "$target" "$GENERATED_SETTINGS"; then
      echo "ok      $target was generated by this repository"
    else
      carry="$target"
      echo "would   fold unmanaged $target into $LOCAL_SETTINGS"
    fi
  fi
  if [ "$APPLY" = true ]; then
    if [ -n "$carry" ]; then
      "$PYTHON" "$ROOT/scripts/sync_config.py" \
        --base "$ROOT/.claude/settings.json" --local "$LOCAL_SETTINGS" \
        --carry "$carry" --output "$GENERATED_SETTINGS"
    else
      "$PYTHON" "$ROOT/scripts/sync_config.py" \
        --base "$ROOT/.claude/settings.json" --local "$LOCAL_SETTINGS" \
        --output "$GENERATED_SETTINGS"
    fi
    mkdir -p "$(dirname -- "$target")"
    cp "$GENERATED_SETTINGS" "$target.tmp"
    mv "$target.tmp" "$target"
    echo "installed $target"
  else
    echo "would   merge portable settings with $LOCAL_SETTINGS"
    echo "would   install merged settings at $target"
  fi
}

install_mcp() {
  if [ "$APPLY" = false ]; then
    echo "would   add user MCP servers: context7, codebase_memory"
    echo "would   add user MCP server github only when GITHUB_PAT_TOKEN is set"
    return
  fi
  command -v claude >/dev/null 2>&1 || {
    echo "Claude Code CLI is required for --apply; install it and rerun." >&2
    return 1
  }
  claude mcp add --transport http --scope user context7 https://mcp.context7.com/mcp
  claude mcp add --transport stdio --scope user codebase_memory -- npx -y codebase-memory-mcp@0.8.1
  if [ -n "${GITHUB_PAT_TOKEN:-}" ]; then
    claude mcp add-json --scope user github \
      '{"type":"http","url":"https://api.githubcopilot.com/mcp/","headers":{"Authorization":"Bearer ${GITHUB_PAT_TOKEN}"}}'
  fi
}

if [ "$APPLY" = true ]; then
  echo "Portable Claude Code bootstrap (apply)"
else
  echo "Portable Claude Code bootstrap (dry-run)"
fi

install_settings || exit 1
link_item "$ROOT/CLAUDE.global.md" "$HOME/.claude/CLAUDE.md" || conflicts=$((conflicts + 1))
link_item "$ROOT/.claude/hooks" "$HOME/.claude/hooks" || conflicts=$((conflicts + 1))
link_children "$ROOT/.claude/agents" "$HOME/.claude/agents" || conflicts=$((conflicts + 1))
link_children "$ROOT/skills" "$HOME/.claude/skills" || conflicts=$((conflicts + 1))

if [ "$conflicts" -ne 0 ]; then
  echo "Found $conflicts conflict(s); nothing was overwritten." >&2
  exit 1
fi

install_mcp || exit 1

if [ "$APPLY" = false ]; then
  echo "Dry-run only. Install Claude Code, then rerun with --apply after resolving conflicts."
fi
