#!/usr/bin/env python3
"""Merge a portable Codex config with a machine-local overlay."""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
import tomllib
from pathlib import Path


BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")
RUNTIME_KEYS = ("hooks",)


def load(path: Path, *, required: bool) -> dict:
    if not path.exists():
        if required:
            raise FileNotFoundError(path)
        return {}
    with path.open("rb") as handle:
        return tomllib.load(handle)


def merge(local: dict, portable: dict) -> dict:
    """Recursively merge configs, with the portable config authoritative."""
    result = copy.deepcopy(local)
    for key, value in portable.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def runtime_overlay(output: Path) -> dict:
    """Retain Codex-owned state that is written into the active config."""
    current = load(output, required=False)
    return {name: current[name] for name in RUNTIME_KEYS if name in current}


def is_current(output: Path, expected: dict) -> bool:
    return load(output, required=False) == expected


def key(value: str) -> str:
    return value if BARE_KEY.fullmatch(value) else json.dumps(value)


def scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(scalar(item) for item in value) + "]"
    if hasattr(value, "isoformat"):
        return value.isoformat()
    raise TypeError(f"unsupported TOML value: {type(value).__name__}")


def render(data: dict) -> str:
    lines = [
        "# Generated by scripts/sync_config.py; do not edit directly.",
        "# Portable values override matching machine-local values.",
        "",
    ]

    def emit_table(table: dict, path: tuple[str, ...], *, header: bool) -> None:
        values = [(name, value) for name, value in table.items() if not isinstance(value, dict)]
        children = [(name, value) for name, value in table.items() if isinstance(value, dict)]

        if header:
            lines.append("[" + ".".join(key(part) for part in path) + "]")
        for name, value in values:
            lines.append(f"{key(name)} = {scalar(value)}")
        if header or values:
            lines.append("")

        for name, child in children:
            emit_table(child, (*path, name), header=True)

    emit_table(data, (), header=False)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", type=Path, required=True)
    parser.add_argument("--local", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    machine = merge(runtime_overlay(args.output), load(args.local, required=False))
    expected_data = merge(machine, load(args.base, required=True))
    if args.check:
        if not is_current(args.output, expected_data):
            print(f"stale   {args.output}; run scripts/bootstrap.sh --apply", file=sys.stderr)
            return 1
        print(f"ok      merged config is current: {args.output}")
        return 0

    expected = render(expected_data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.output.with_name(args.output.name + ".tmp")
    temporary.write_text(expected, encoding="utf-8")
    temporary.replace(args.output)
    print(f"merged  {args.output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, TypeError, tomllib.TOMLDecodeError) as error:
        print(f"config merge failed: {error}", file=sys.stderr)
        raise SystemExit(1)
