#!/usr/bin/env python3
"""Merge a portable provider config with a machine-local overlay.

Claude Code stores settings as JSON and Codex stores them as TOML. The merge
semantics are identical, so only loading and rendering dispatch on the file
extension; everything below `merge` is shared by both providers.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
import tomllib
from pathlib import Path


BARE_KEY = re.compile(r"^[A-Za-z0-9_-]+$")


def fmt(path: Path) -> str:
    suffix = path.suffix.lower()
    if suffix in (".toml", ""):
        return "toml"
    if suffix == ".json":
        return "json"
    raise TypeError(f"{path} must be a .json or .toml file")


def load(path: Path, *, required: bool) -> dict:
    if not path.exists():
        if required:
            raise FileNotFoundError(path)
        return {}
    if fmt(path) == "toml":
        with path.open("rb") as handle:
            return tomllib.load(handle)
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"{path} must contain a JSON object")
    return value


def union(local: list, portable: list) -> list:
    """Append portable entries the local list does not already contain.

    Replacing lists loses machine-local data that has no portable counterpart:
    an unrelated `hooks.SessionStart` handler, or an accumulated
    `permissions.allow` list. Both layers are kept, local first, and repeated
    runs stay idempotent because equal entries are only carried once.
    """
    result = copy.deepcopy(local)
    for value in portable:
        if value not in result:
            result.append(copy.deepcopy(value))
    return result


def merge(local: dict, portable: dict) -> dict:
    result = copy.deepcopy(local)
    for key, value in portable.items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        elif isinstance(value, list) and isinstance(result.get(key), list):
            result[key] = union(result[key], value)
        else:
            result[key] = copy.deepcopy(value)
    return result


def toml_key(value: str) -> str:
    return value if BARE_KEY.fullmatch(value) else json.dumps(value)


def toml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(toml_scalar(item) for item in value) + "]"
    if hasattr(value, "isoformat"):
        return value.isoformat()
    raise TypeError(f"unsupported TOML value: {type(value).__name__}")


def render_toml(data: dict) -> str:
    lines = [
        "# Generated by scripts/sync_config.py; do not edit directly.",
        "# Portable values override matching machine-local values.",
        "",
    ]

    def is_array_of_tables(value: object) -> bool:
        return isinstance(value, list) and bool(value) and all(isinstance(item, dict) for item in value)

    def emit_table(table: dict, path: tuple[str, ...], *, header: bool, array: bool = False) -> None:
        values = [
            (name, value)
            for name, value in table.items()
            if not isinstance(value, dict) and not is_array_of_tables(value)
        ]
        children = [(name, value) for name, value in table.items() if isinstance(value, dict)]
        arrays = [(name, value) for name, value in table.items() if is_array_of_tables(value)]

        if header:
            brackets = "[[{}]]" if array else "[{}]"
            lines.append(brackets.format(".".join(toml_key(part) for part in path)))
        for name, value in values:
            lines.append(f"{toml_key(name)} = {toml_scalar(value)}")
        if header or values:
            lines.append("")

        for name, child in children:
            emit_table(child, (*path, name), header=True)

        for name, items in arrays:
            for item in items:
                emit_table(item, (*path, name), header=True, array=True)

    emit_table(data, (), header=False)
    return "\n".join(lines).rstrip() + "\n"


def render(data: dict, path: Path) -> str:
    if fmt(path) == "toml":
        return render_toml(data)
    return json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def write(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(render(data, path), encoding="utf-8")
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", type=Path, required=True)
    parser.add_argument("--local", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--carry",
        type=Path,
        help="Unmanaged settings to fold underneath the machine-local overlay before merging. "
        "The overlay wins on matching keys; the result is written back to --local.",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    overlay = load(args.local, required=False)
    if args.carry is not None and not args.check:
        carried = merge(load(args.carry, required=False), overlay)
        if carried != overlay:
            write(args.local, carried)
            print(f"carried {args.carry} into {args.local}")
        overlay = carried
    expected_data = merge(overlay, load(args.base, required=True))
    if args.check:
        if load(args.output, required=False) != expected_data:
            print(f"stale   {args.output}; run scripts/bootstrap.sh --apply", file=sys.stderr)
            return 1
        print(f"ok      merged settings are current: {args.output}")
        return 0
    write(args.output, expected_data)
    print(f"merged  {args.output}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, TypeError, json.JSONDecodeError) as error:
        print(f"settings merge failed: {error}", file=sys.stderr)
        raise SystemExit(1)
